name: api_request_helper_flutter
description: Flutter package for handling http calls such as GET, POST, PUT, DELETE.
version: 0.2.1+3
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  very_good_analysis: ^5.0.0+1
